# Generated by Django 5.2.3 on 2025-09-16 21:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0014_blog_exclude_from_news_blog_is_breaking_news_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('position_type', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('in_content', 'In Content'), ('between_posts', 'Between Posts'), ('popup', 'Popup Modal'), ('sticky', 'Sticky/Fixed Position')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(help_text='Width in pixels')),
                ('height', models.PositiveIntegerField(help_text='Height in pixels')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ad_type', models.CharField(choices=[('image', 'Image Banner'), ('html', 'HTML/Rich Content'), ('video', 'Video'), ('script', 'Third-party Script (Google Ads, etc.)')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/')),
                ('html_content', models.TextField(blank=True, help_text='HTML content for rich ads')),
                ('script_content', models.TextField(blank=True, help_text='JavaScript/Third-party code')),
                ('click_url', models.URLField(blank=True, help_text='Where the ad links to')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_on_blog_posts', models.BooleanField(default=True)),
                ('show_on_categories', models.BooleanField(default=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.adposition')),
                ('target_categories', models.ManyToManyField(blank=True, to='blogs.category')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.advertisement')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.advertisement')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
