# Generated by Django 5.2.3 on 2025-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
