# Generated by Django 5.2.3 on 2025-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
