# Generated by Django 5.2.3 on 2025-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_sociallink_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
