# Generated by Django 5.2.3 on 2025-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_sitesetting_meta_author_sitesetting_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
