# Generated by Django 5.2.3 on 2025-08-09 20:02

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_base_name',
            field=models.CharField(blank=True, editable=False, help_text='SEO_friendly base name for the feautred image (auto fill)', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Original image height in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Original image width in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d', validators=[blogs.models.validate_image_extension]),
        ),
    ]
