# Generated by Django 5.2.3 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_image_base_name_blog_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Original image width in pixels.', null=True),
        ),
    ]
