# Generated by Django 5.2.3 on 2025-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blog_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for auto-linking', max_length=255),
        ),
    ]
