# Generated by Django 5.2.3 on 2025-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blog_seo_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main SEO keyword for this post', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=125),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max)', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max)', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console',
            field=models.TextField(blank=True, help_text='Google Search Console verification code'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Logo for social sharing', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='My Blog', help_text='Site name for SEO', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Default author name', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Default site description', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Default site keywords', max_length=255),
        ),
    ]
