# Generated by Django 5.2.3 on 2025-09-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_options_blog_focus_keyword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
