# Generated by Django 5.2.3 on 2025-09-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_delete_comment'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='exclude_from_news',
            field=models.BooleanField(default=False, help_text='Exclude from Google News sitemap'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_breaking_news',
            field=models.BooleanField(default=False, help_text='Mark as breaking news'),
        ),
        migrations.AddField(
            model_name='blog',
            name='news_genre',
            field=models.CharField(blank=True, help_text='News genre (e.g., PressRelease, Satire, Blog, Opinion)', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='news_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('breaking', 'Breaking')], default='medium', help_text='News priority level', max_length=20),
        ),
        migrations.CreateModel(
            name='CoreWebVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('session_id', models.CharField(max_length=255)),
                ('lcp', models.FloatField(blank=True, null=True)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('fcp', models.FloatField(blank=True, null=True)),
                ('ttfb', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('connection_type', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['url', 'timestamp'], name='blogs_corew_url_513cbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('article_read', 'Article Read'), ('comment_posted', 'Comment Posted'), ('newsletter_signup', 'Newsletter Signup'), ('search_performed', 'Search Performed'), ('link_clicked', 'Link Clicked'), ('download', 'Download'), ('scroll_depth', 'Scroll Depth'), ('time_on_page', 'Time on Page'), ('voice_search', 'Voice Search')], max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_data', models.JSONField(default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='blogs_analy_event_t_92a9b5_idx'), models.Index(fields=['content_type', 'object_id'], name='blogs_analy_content_34abe5_idx'), models.Index(fields=['session_id'], name='blogs_analy_session_bf60e6_idx')],
            },
        ),
    ]
