# Generated by Django 5.2.3 on 2025-10-11 19:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_brokenlink_linkopportunity_linkperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
