# Generated by Django 5.2.3 on 2025-12-26 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_blog_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('mixed', 'Article with Video')], default='article', help_text='Type of content (auto-detected based on video)', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_duration',
            field=models.DurationField(blank=True, help_text='Video duration (automatically calculated for uploaded videos)', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM, OGG, MOV, AVI)', null=True, upload_to='blog_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi'])]),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for video (optional, will use featured_image if not provided)', null=True, upload_to='video_thumbnails/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or provide YouTube/Vimeo URL (e.g., https://www.youtube.com/watch?v=xxxxx)', null=True),
        ),
    ]
