# Generated by Django 5.2.3 on 2025-12-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_blog_content_type_blog_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='geo_locations',
            field=models.CharField(blank=True, help_text='Geographic locations relevant to this story (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='news_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for Google News', max_length=255),
        ),
    ]
