# Generated by Django 5.2.3 on 2026-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main SEO keyword for this post', max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (250 chars max)', max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
