# Generated by Django 5.2.3 on 2026-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_alter_blog_focus_keyword_alter_blog_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (160 chars max)', max_length=250),
        ),
    ]
