# Generated by Django 5.2.3 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='form_header_icon',
            field=models.ImageField(blank=True, help_text="Upload an icon for the 'Add User' form header.", null=True, upload_to='profile/icons/'),
        ),
    ]
