# Generated by Django 5.2.3 on 2025-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_form_header_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='form_header_icon',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
