# Generated by Django 5.2.3 on 2025-08-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_image_height_profile_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
