# Generated by Django 5.2.3 on 2025-09-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_ban_until',
            field=models.DateTimeField(blank=True, help_text='User is banned from commenting until this date', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_mention',
            field=models.BooleanField(default=True, help_text='Receive email when mentioned in a comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_reply',
            field=models.BooleanField(default=True, help_text='Receive email when someone replies to your comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_comment_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
