# Generated by Django 5.2.3 on 2025-09-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_comment_ban_until_profile_email_on_mention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='avatars/'),
        ),
    ]
