# Generated by Django 5.2.3 on 2025-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='avatars/'),
        ),
    ]
