"""
Django settings for blogmain project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config  # ADD THIS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'taggit',
    'blogs.apps.BlogConfig',
    'comments.apps.CommentsConfig',
    'assignment',
    'crispy_forms',
    'dashboards',
    'pages',
    'crispy_bootstrap4',
    'django_ckeditor_5',
    'ads',  # Add this line - your new ads app
    'notifications',
    'django.contrib.sitemaps',
    'pipeline',
    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'accounts.apps.AccountsConfig',
    # Providers (Google and Facebook)
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# MIDDLEWARE - Cleaned up version
# MIDDLEWARE - CORRECTED ORDER (Replace your MIDDLEWARE section)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Cache middleware MUST come right after SessionMiddleware
    'django.middleware.cache.UpdateCacheMiddleware',  # MUST be before CommonMiddleware
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
    # Custom middleware (after authentication)
    'accounts.middleware.AuthAwareCacheMiddleware',
    'dashboards.middleware.AdminNoCacheMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # FetchFromCacheMiddleware MUST be last (or near last)
    'django.middleware.cache.FetchFromCacheMiddleware',  # MUST be after all other middleware
    
    # Comment rate limiting - TEMPORARILY DISABLED FOR TESTING
    # 'comments.middleware.CommentRateLimitMiddleware',  # Enable after testing works
]

ROOT_URLCONF = 'blogmain.urls'

# Push Notification Settings
WEBPUSH_SETTINGS = {
    'VAPID_PRIVATE_KEY': config('VAPID_PRIVATE_KEY'),
    'VAPID_PUBLIC_KEY': config('VAPID_PUBLIC_KEY'),
    'VAPID_ADMIN_EMAIL': config('VAPID_ADMIN_EMAIL')
}

# Advertisement Settings
ADS_SETTINGS = {
    'ENABLE_VIEWABILITY_TRACKING': True,
    'VIEWABILITY_THRESHOLD': 0.5,  # 50% of ad must be visible
    'VIEWABILITY_DURATION': 1000,  # 1 second
    'MAX_CLICKS_PER_IP_PER_DAY': 10,
    'MAX_IMPRESSIONS_PER_IP_PER_HOUR': 100,
    'ENABLE_AD_BLOCKER_DETECTION': True,
    'DEFAULT_AD_EXPIRY_DAYS': 30,
    'ANALYTICS_RETENTION_DAYS': 90,
    'ENABLE_GEOGRAPHIC_TARGETING': False,
    'ENABLE_DEVICE_TARGETING': False,
}

# COMMENT SYSTEM SETTINGS - Consolidated
COMMENTS_SETTINGS = {
    'MAX_DEPTH': 4,
    'MAX_LENGTH': 1000,
    'ALLOW_ANONYMOUS': False,
    'MODERATION_REQUIRED': False,
    'ALLOW_EDITING': True,
    'EDIT_TIME_LIMIT': 15,  # minutes
    'PAGINATION_SIZE': 10,
    'ENABLE_LIKES': True,
    'ENABLE_FLAGS': True,
    'AUTO_APPROVE': True,
    'RATE_LIMIT_SECONDS': 30,  # Seconds between comments
    'SPAM_DETECTION': True,
}

# Individual settings for backward compatibility
COMMENTS_MAX_DEPTH = COMMENTS_SETTINGS['MAX_DEPTH']
COMMENTS_MAX_LENGTH = COMMENTS_SETTINGS['MAX_LENGTH']
COMMENTS_ALLOW_ANONYMOUS = COMMENTS_SETTINGS['ALLOW_ANONYMOUS']
COMMENTS_MODERATION_REQUIRED = COMMENTS_SETTINGS['MODERATION_REQUIRED']
COMMENTS_ALLOW_EDITING = COMMENTS_SETTINGS['ALLOW_EDITING']
COMMENTS_EDIT_TIME_LIMIT = COMMENTS_SETTINGS['EDIT_TIME_LIMIT']


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blogs.context_processors.get_categories',
                'blogs.context_processors.get_social_links',
                'blogs.context_processors.site_settings',
                'ads.context_processors.ad_settings',  # Add this line
                'notifications.context_processors.webpush_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogmain.wsgi.application'



# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
    }
}

# Cache Configuration - Choose one based on your setup
if DEBUG:
    # Development: Use local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,  # 5 minutes default timeout
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }
else:
    # Production: Use Redis cache (requires Redis installation)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'blog_cache',
            'TIMEOUT': 300,
            'VERSION': 1,
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/2',
            'TIMEOUT': 86400,  # 24 hours
        },
        'analytics': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/3',
            'TIMEOUT': 3600,  # 1 hour
        }
    }

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'default'
#CACHE_MIDDLEWARE_SECONDS = 300 if not DEBUG else 0  # 5 minutes in production, disabled in debug
CACHE_MIDDLEWARE_SECONDS = 0  # Disable cache middleware temporarily
CACHE_MIDDLEWARE_KEY_PREFIX = 'blog'
CACHE_MIDDLEWARE_ANONYMOUS_ONLY = True

# Cache control for specific URLs
CACHE_CONTROL_URLS = {
    '/dashboard/': {'max_age': 0, 'no_cache': True},
    '/admin/': {'max_age': 0, 'no_cache': True},
    '/accounts/': {'max_age': 0, 'no_cache': True},
}

# Cache utility functions
def get_cache_key(request, view_name=None):
    """Generate cache keys that are user and permission aware"""
    key_parts = [
        request.path,
        f"user_{request.user.id}" if request.user.is_authenticated else "anonymous",
        f"staff_{request.user.is_staff}" if request.user.is_authenticated else "",
        view_name or ""
    ]
    return "_".join(filter(None, key_parts))

def make_cache_key(request, *args, **kwargs):
    """Custom cache key that includes authentication state"""
    cache_key = f"{request.path}_{request.user.pk if request.user.is_authenticated else 'anonymous'}"
    if request.GET:
        cache_key += f"_{hash(frozenset(request.GET.items()))}"
    return cache_key

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Include multiple static directories (one per app)
STATICFILES_DIRS = [
    BASE_DIR / 'blogmain' / 'static',
]

# For collectstatic in production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload limits (100MB for videos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

# Pipeline configuration in settings.py
PIPELINE = {
    'PIPELINE_ENABLED': not DEBUG,  # Enable compression in production only
    'CSS_COMPRESSOR': 'pipeline.compressors.cssmin.CSSMinCompressor',
    'JS_COMPRESSOR': 'pipeline.compressors.jsmin.JSMinCompressor',
    'COMPILERS': [],
    'STYLESHEETS': {
        'main': {
            'source_filenames': (
                'css/base.css',
                'css/dashboard.css',
                'css/home.css',
                'css/blog.css',
                'css/page.css',
                'css/tagged_posts.css',
                'css/pagess.css',
                'css/login.css',
                'css/signup.css',
                'css/unsubscribed.css',
                'css/seo_admin.css',
                'css/comment.css',
                'css/blog-components.css',
                'css/profile.css',
                'css/advanced-features.css',
                'css/advertisements.css',
                'css/analytics-ads.css',
                'css/notifications.css',  # ADD THIS
                'css/video.css',
            ),
            'output_filename': 'css/main.min.css',
            'extra_context': {
                'media': 'screen,projection',
            },
        },
    },
    'JAVASCRIPT': {
        'main': {
            'source_filenames': (
                'js/base.js',
                'js/blog.js',
                'js/home.js',
                'js/comment.js',
                'js/blog-components.js',
                'js/dashboard.js',
                'js/analytics-manager.js',
                'js/pwa-manager.js',
                'js/voice-search.js',
                'js/push-notifications.js',
                'js/notification-manager.js',  # ADD THIS
                
            ),
            'output_filename': 'js/main.min.js',
        },
    },
}

# Make sure Pipeline finder is in STATICFILES_FINDERS
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',  # This is crucial
]

# Add Pipeline storage for production
if not DEBUG:
    STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'Bootstrap4'

# Django Sites Framework
SITE_ID = 2

# Authentication
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
)

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Allauth settings
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_ADAPTER = "accounts.adapters.MySocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
    'login': 'accounts.forms.CustomLoginForm',
}

SOCIALACCOUNT_FORMS = {
    'signup': 'accounts.forms.SocialSignupForm',
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production - uncomment and configure these:
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bidemia02@gmail.com'
EMAIL_HOST_PASSWORD = 'baci akdd twoo yqmr'  # Use app password, not your regular password
"""

DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'
SITE_NAME = 'Your Blog Name'
SITE_URL = 'http://127.0.0.1:8000/'  # Change to your domain in production

# Email Configuration for Error Reporting (Production)
ADMINS = [
    ('Your Name', 'your-email@example.com'),
]
SERVER_EMAIL = 'noreply@yourdomain.com'
EMAIL_SUBJECT_PREFIX = '[Blog Error] '

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CSRF settings
CSRF_COOKIE_SECURE = False  # Set to True only in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token if needed
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Keep CSRF tokens in cookies
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']

# Enhanced Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True

# Pagination Settings
PAGINATE_BY = 10

# Tags
TAGGIT_CASE_INSENSITIVE = True

# Custom Settings for Blog App
BLOG_SETTINGS = {
    'FEATURED_POSTS_COUNT': 1,
    'TRENDING_POSTS_COUNT': 2,
    'EDITORS_PICKS_COUNT': 5,
    'CATEGORY_POSTS_COUNT': 6,
    'CACHE_TIMEOUT': 900,  # 15 minutes
    'ENABLE_COMMENTS': True,
    'ENABLE_SOCIAL_SHARING': True,
}

# PWA Configuration
PWA_CONFIG = {
    'name': 'Advanced Blog PWA',
    'short_name': 'BlogPWA',
    'description': 'Advanced blogging platform with AI features',
    'theme_color': '#000000',
    'background_color': '#ffffff',
    'display': 'standalone',
    'start_url': '/',
    'icons': [
        {
            'src': '/static/images/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png'
        },
        {
            'src': '/static/images/icon-512x512.png',
            'sizes': '512x512', 
            'type': 'image/png'
        }
    ]
}

# Analytics Configuration
GA4_MEASUREMENT_ID = 'G-XXXXXXXXXX'  # Replace with your GA4 ID
GA4_API_SECRET = 'your-api-secret'  # Replace with your API secret
ANALYTICS_ENABLED = True

# AI Content Intelligence
AI_CONTENT_SETTINGS = {
    'ENABLE_CONTENT_ANALYSIS': True,
    'AUTO_ANALYZE_NEW_POSTS': True,
    'MINIMUM_CONTENT_SCORE': 70,
    'OPENAI_API_KEY': '',  # Add your OpenAI API key for advanced features
}

# Voice Search Configuration
VOICE_SEARCH_SETTINGS = {
    'ENABLE_VOICE_SEARCH': True,
    'SUPPORTED_LANGUAGES': ['en-US', 'en-GB'],
    'VOICE_TIMEOUT': 5000,  # milliseconds
}

# Link Building Configuration
LINK_BUILDING_SETTINGS = {
    'ENABLE_AUTO_LINKING': True,
    'MAX_INTERNAL_LINKS_PER_POST': 10,
    'MIN_RELEVANCE_SCORE': 0.3,
    'CHECK_BROKEN_LINKS_INTERVAL': 24,  # hours
}

# Performance Settings
PERFORMANCE_SETTINGS = {
    'ENABLE_IMAGE_OPTIMIZATION': True,
    'WEBP_QUALITY': 80,
    'JPEG_QUALITY': 85,
    'ENABLE_LAZY_LOADING': True,
    'PRELOAD_CRITICAL_RESOURCES': True,
}

# Security Settings
SECURITY_SETTINGS = {
    'ENABLE_RATE_LIMITING': True,
    'ENABLE_CSP': True,
    'ENABLE_SECURITY_HEADERS': True,
    'MAX_REQUEST_SIZE': 5 * 1024 * 1024,  # 5MB
}

# News Sitemap Settings
NEWS_SITEMAP_SETTINGS = {
    'ENABLE_NEWS_SITEMAP': True,
    'NEWS_SITEMAP_DAYS_BACK': 2,
    'NEWS_SITEMAP_MAX_ARTICLES': 1000,
    'NEWS_SITEMAP_CACHE_TIMEOUT': 1800,  # 30 minutes
    'NEWS_CATEGORIES': [
        'News', 'Breaking News', 'Current Events', 'Technology News',
        'Business News', 'Politics', 'Health News', 'Sports News',
        'Entertainment News', 'Science News', 'Tech', 'Technology'
    ],
}

# Image Optimization Settings
THUMBNAIL_ENGINE = 'sorl.thumbnail.engines.pil_engine.engine'
THUMBNAIL_KEY_PREFIX = 'thumbnail-cache'

# Django Messages
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Enhanced Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/django.log',
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/security.log',
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'performance': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/performance.log',
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': True,
        },
        'blogs.performance': {
            'handlers': ['performance'],
            'level': 'INFO',
            'propagate': True,
        },
        'blogs.ai_content': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },   
}

LOGGING['loggers']['ads'] = {
    'handlers': ['file'],
    'level': 'INFO',
    'propagate': True,
}

LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# Add comments logger
LOGGING['loggers']['comments'] = {
    'handlers': ['file', 'console'],
    'level': 'DEBUG',  # Set to DEBUG for troubleshooting
    'propagate': False,
}

# CKEditor 5 Configuration
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "underline", 
            "strikethrough",
            "code",
            "subscript", 
            "superscript", 
            "highlight", 
            "|", 
            "codeBlock", 
            "sourceEditing", 
            "insertImage",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload",
            "|",
            "fontSize", 
            "fontFamily", 
            "fontColor", 
            "fontBackgroundColor", 
            "mediaEmbed", 
            "removeFormat",
            "insertTable",
            "undo",
            "redo",
        ],
        'image': {
            'toolbar': ['imageTextAlternative', 'imageStyle:full', 'imageStyle:side']
        },
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Paragraph", "class": "ck-heading_paragraph"},
                {"model": "heading1", "view": "h1", "title": "Heading 1", "class": "ck-heading_heading1"},
                {"model": "heading2", "view": "h2", "title": "Heading 2", "class": "ck-heading_heading2"},
            ]
        },
    }
}